<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/MiniProject1(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#creating a 5x5 matrix with random integers from 1 to 50 filled inbetween them
arr=np.random.randint(1,50,(5,5))
print("The array is :")
print(arr)
arr=np.where(arr%2==0,-1,arr)
print("Array after replacing every even number with -1")
print(arr)
row_sum=np.sum(arr,axis=1)
row_sum_list=row_sum.tolist()
print("List representing sum of elements of each row")
print(row_sum_list)
transpose_arr=np.transpose(arr)
dot_product=np.dot(arr,transpose_arr)
print("The dot product of the matrix and its transpose is")
print(dot_product)
m=np.max(arr)
i=np.argwhere(arr==m)
print("The index of maximum element in the matrix is")
print(i)

The array is :
[[12 19 32 16 32]
 [27 24  4  9 13]
 [17  6 22  8 34]
 [33 15 30 35  9]
 [40 27 20 46 12]]
Array after replacing every even number with -1
[[-1 19 -1 -1 -1]
 [27 -1 -1  9 13]
 [17 -1 -1 -1 -1]
 [33 15 -1 35  9]
 [-1 27 -1 -1 -1]]
List representing sum of elements of each row
[15, 47, 13, 91, 23]
The dot product of the matrix and its transpose is
[[ 365  -67  -33  209  517]
 [ -67  981  439 1309  -75]
 [ -33  439  293  503  -41]
 [ 209 1309  503 2621  329]
 [ 517  -75  -41  329  733]]
The index of maximum element in the matrix is
[[3 3]]
