<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/MiniProject2(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
columns=["Morning","Afternoon","Evening","Night"]
arr=np.random.randint(0,40,(30,4))
print("The array containing data:")
print(arr)
avg_temp=np.mean(arr,axis=1)
for name,avg in zip(columns,avg_temp):
  print("The average temp of",name,"is",avg)
avg_daily=np.mean(arr,axis=1)
maximum=np.argmax(avg_daily)+1
minimum=np.argmin(avg_daily)+1
print("The hotest day was on day",maximum)
print("The coldest day was on day",minimum)
temp=np.where(arr[:,1]>35)[0]+1
print("The days on which afternoon temperature exceeded 35 degree celsius:",temp)
moving_avg=np.convolve(avg_daily,np.ones(7)/7,mode='valid')
print("The moving average of temperature over a 7 day window:")
print(moving_avg)

The array containing data:
[[ 6  2 36  1]
 [19 28 34  6]
 [ 1 30 31  9]
 [14  5 23 10]
 [20  3 18 36]
 [23 10  9 34]
 [34  5 12 11]
 [15  0 18 24]
 [39  2 22  4]
 [18 34 15 31]
 [ 8 31  3 14]
 [29 22 35 15]
 [14 12 19  3]
 [34 26  2 26]
 [14  1  0 19]
 [29  4 20 20]
 [35 35  6 23]
 [17  1  9 32]
 [ 9 21 30 20]
 [25 25 25  5]
 [32  8 14 33]
 [29 27 30 39]
 [11  3  3 14]
 [20 24 17 26]
 [ 3 17 25 29]
 [ 5 13 38  4]
 [35 14 28 28]
 [ 5 11 36 26]
 [17 28 37 34]
 [14  4 19  4]]
The average temp of Morning is 11.25
The average temp of Afternoon is 21.75
The average temp of Evening is 17.75
The average temp of Night is 13.0
The hotest day was on day 22
The coldest day was on day 23
The days on which afternoon temperature exceeded 35 degree celsius: []
The moving average of temperature over a 7 day window:
[16.78571429 17.21428571 16.5        17.46428571 17.60714286 18.46428571
 17.46428571 18.39285714 17.57142857 17.78571429 17.82142857 17.92857143
 17.17857143 18.32142857 18.28571429 21.5357