<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#basic way of declaring array
a=np.array([1,2,3])
print(a)


[1 2 3]


In [3]:
#dimensions of array
print(a.ndim)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

1
[[1 2 3]
 [4 5 6]]
2


Homework try two dimensional matrix to find the conditional statements