<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Matrix Calculator – Develop a program that performs addition, multiplication, determinant, transpose and inverse operations on matrices

In [1]:
import numpy as np

In [2]:
#function to perform addition of matrix
def add_matrix(matrix1, matrix2):
    return np.add(matrix1, matrix2)

In [3]:
#function to perform multiplication
def mul_matrix(matrix1,matrix2):
    return np.dot(matrix1,matrix2)

In [4]:
#function to find determinant of a matrix
def det_matrix(matrix3):
  return np.linalg.det(matrix3)

In [5]:
#function to find the transpose
def trans_matrix(matrix3):
  return matrix3.transpose()

In [6]:
#function to find inverse of a matrix
def inv_matrix(matrix3):
  if np.linalg.det(matrix3) == 0:
    print("Inverse does not exist")
  else:
    return np.linalg.inv(matrix3)

In [21]:
row1=int(input("Enter the number of rows of matrix1: "))
column1=int(input("Enter the number of columns of matrix1: "))
row2=int(input("Enter the number of rows of matrix2: "))
column2=int(input("Enter the number of columns of matrix2: "))
matrix1 = np.zeros((row1, column1), dtype=int)
matrix2 = np.zeros((row2, column2), dtype=int)
for i in range(row1):
    for j in range(column1):
        matrix1[i][j]=int(input(f"Enter element [{i}][{j}] for matrix1: "))
for i in range(row2):
    for j in range(column2):
        matrix2[i][j]=int(input(f"Enter element [{i}][{j}] for matrix2: "))
obj1=add_matrix(matrix1,matrix2)
obj2=mul_matrix(matrix1,matrix2)
obj3=det_matrix(matrix1)
obj4=trans_matrix(matrix1)
obj5=inv_matrix(matrix1)
print("Matrix 1 is")
print(matrix1)
print("Matrix 2 is")
print(matrix2)
print("Addition of matrix is ")
print(obj1)
print("Multiplication of matrix is")
print(obj2)
print("Determinant of matrix is")
print(obj3)
print("Transpose of matrix is")
print(obj4)
print("Inverse of matrix is")
print(obj5)

Enter the number of rows of matrix1: 2
Enter the number of columns of matrix1: 2
Enter the number of rows of matrix2: 2
Enter the number of columns of matrix2: 2
Enter element [0][0] for matrix1: 1
Enter element [0][1] for matrix1: 2
Enter element [1][0] for matrix1: 3
Enter element [1][1] for matrix1: 4
Enter element [0][0] for matrix2: 5
Enter element [0][1] for matrix2: 6
Enter element [1][0] for matrix2: 7
Enter element [1][1] for matrix2: 8
Matrix 1 is
[[1 2]
 [3 4]]
Matrix 2 is
[[5 6]
 [7 8]]
Addition of matrix is 
[[ 6  8]
 [10 12]]
Multiplication of matrix is
[[19 22]
 [43 50]]
Determinant of matrix is
-2.0000000000000004
Transpose of matrix is
[[1 3]
 [2 4]]
Inverse of matrix is
[[-2.   1. ]
 [ 1.5 -0.5]]
