<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/Project4(sudoko_solver).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Enter the Sudoku puzzle row by row, using 0 for empty cells:")
puzzle = []
for _ in range(9):
    row = list(map(int, input().split()))
    puzzle.append(row)
board = np.array(puzzle, dtype=int)
empty_cells = np.argwhere(board == 0)
def backtrack(index):
    if index == len(empty_cells):
        return True
    row, col = empty_cells[index]
    for num in range(1, 10):
        if (num not in board[row, :]) and (num not in board[:, col]) and (num not in board[(row//3)*3:(row//3)*3+3, (col//3)*3:(col//3)*3+3]):
            board[row, col] = num
            if backtrack(index + 1):
                return True

            board[row, col] = 0
    return False
if backtrack(0):
    print("Solved Sudoku:")
    print(board)
else:
    print("No solution found!")


Enter the Sudoku puzzle row by row, using 0 for empty cells:
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
Solved Sudoku:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 4 2 9 7 8 5 3 1]
 [9 7 8 5 3 1 6 4 2]]
