<a href="https://colab.research.google.com/github/Ruthi-N/Numpy-projects/blob/main/Project1(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating array in numpy
import numpy as np
#1 dimesional without specifying data types
a=np.array([1,2,3,4,5])
print('a',a)
#1 dimensional specifying dataype
b=np.array([1,2,3,4,5],dtype=float)
print('b',b)
#2 dimensional
c=np.array([[1,2,3],[4,5,6]])
print('c',c)
#2 dimensional array using a loop
d=np.array([range(i,i+3) for i in [2,4,6]])
print('d',d)
# creating a array filled with zeros in a specified size
e=np.zeros(10,dtype=float)
print('e',e)
f=np.zeros((3,5),dtype=int)
print('f',f)
#creating a array filled with ones
g=np.ones((5,8),dtype=int)
print('g',g)
#creating an array to have the sam value filled in the whole array
h=np.full(5,6)
print('h',h)
#creating an array filled with linear sequence using start stop and step(this can create only one dimesional arrays directly)
i=np.arange(0,20,2)
print('i',i)
#creating arrays of values evenly spaced
j=np.linspace(0,10,5)
print('j',j)
#creating an array of random values
k=np.random.random(4)#makes a matrix of order 4 with values in between 0 to 1 filled in them
print('k',k)
l=np.random.normal(1,10,(3,3))#creates a amtrix of order 3,3 with values in between 1 and 10
print('l',l)
m=np.random.randint(1,5,(6,7))#creates a matrix of order 6,7 ith values in between 1 and 5
print('m',m)
n=np.eye(3,3)
print('n',n)


a [1 2 3 4 5]
b [1. 2. 3. 4. 5.]
c [[1 2 3]
 [4 5 6]]
d [[2 3 4]
 [4 5 6]
 [6 7 8]]
e [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
f [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
g [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
h [6 6 6 6 6]
i [ 0  2  4  6  8 10 12 14 16 18]
j [ 0.   2.5  5.   7.5 10. ]
k [0.02013719 0.12072114 0.0620427  0.24157227]
l [[  0.97371532  -6.97342233 -11.78494147]
 [ 10.35371451  -0.99532137  -2.51580535]
 [  5.63924634  -4.21874613  10.59425045]]
m [[3 3 4 1 1 1 2]
 [1 2 4 4 1 1 4]
 [1 2 1 3 1 3 1]
 [4 2 2 2 1 4 2]
 [3 1 2 2 2 3 3]
 [2 4 2 3 3 4 4]]
n [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

#numpy array attributes
print(c.ndim)
print(f.shape)
print(g.size)
print(h.dtype)
print(a.itemsize)
print(b.nbytes)

2
(3, 5)
40
int64
8
40


In [ ]:
#array indexing
print(a[0])
print(c[1])
print(d[1][2])
#[start:stop:step]
#for 2 dimensional array it is arrayname[row start:row stop:row step,column start:column stop:column step]
print(m[0:6:2,1])

1
[4 5 6]
6
[4 4 2]


In [ ]:
#creating copy of arrays ,editing and modifying arrays
x=a[0:5]
print(x)
x[1]=1000#this method changes the original array as well
print(x)
print(a)
y=a[0:5].copy()#using copy function does no affect the original array if there is any edit made in the copied array
print(y)
y[2]=2000
print(y)
print(a)

[1 2 3 4 5]
[   1 1000    3    4    5]
[   1 1000    3    4    5]
[   1 1000    3    4    5]
[   1 1000 2000    4    5]
[   1 1000    3    4    5]


In [ ]:
#reshaping of arrays
#syntax:arrayname.reshape(no. of rows,no. of columns)
e.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#concatenating or merging 2 arrays
#np.concatenate([array1,array2],axis=0(for row)/1(for column))
print(np.concatenate([a,a],axis=0))
print(np.concatenate([c,c],axis=1))
print(np.concatenate([c,c],axis=0))
#horizontal stack
print(np.hstack(c))
#vertical stack
print(np.vstack(a))

[   1 1000    3    4    5    1 1000    3    4    5]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[   1]
 [1000]
 [   3]
 [   4]
 [   5]]


In [ ]:
#splitting of arrays
#np.split(arrayname,[first index where array should be split, second index where array should be split])
a1,a2,a3=np.split(a,[1,4])
print(a1,a2,a3)
c1,c2=np.hsplit(c,[2])
print(c1,c2)
d1,d2=np.vsplit(d,[2])
print(d1,d2)

[1] [1000    3    4] [5]
[[1 2]
 [4 5]] [[3]
 [6]]
[[2 3 4]
 [4 5 6]] [[6 7 8]]


In [ ]:
#UFuncs
#*
print("a*3",a*3)#np.multiply(a,3)
print("a-10",a-10)#np.subtract(a,10)
print("a+15",a+15)#np.add(a,15)
print("a/2",a/2)#np.divide(a,2)
print("a//3",a//3)#np.floor_divide(a,3)
print("-a",-a)#np.negative(a)
print("x**2",x**2)#np.power(a,2)
print("x%2",x%2)#np.mod(x,2)
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
x11 = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x11))
print("arccos(x) = ", np.arccos(x11))
print("arctan(x) = ", np.arctan(x11))
x12 = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x12))
print("2^x =", np.exp2(x12))
print("3^x =", np.power(3, x12))
x13 = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x13))
print("2^x =", np.exp2(x13))
print("3^x =", np.power(3, x13))
x14 = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x14))
print("log2(x) =", np.log2(x14))
print("log10(x) =", np.log10(x14))

a*3 [   3 3000    9   12   15]
a-10 [ -9 990  -7  -6  -5]
a+15 [  16 1015   18   19   20]
a/2 [  0.5 500.    1.5   2.    2.5]
a//3 [  0 333   1   1   1]
-a [   -1 -1000    -3    -4    -5]
x**2 [      1 1000000       9      16      25]
x%2 [1 0 1 0 1]


In [ ]:
#max ,min and etc
print(np.sum(a))#returns the sum of elements in the array
print(np.max(b))#returns the max of elements in the array
print(np.min(c))#returns the min of elements in the array
print(np.max(a,axis=0))
print(np.min(b,axis=0))

1013
5.0
1
1000
1.0


In [ ]:
#  boolean array
x = np.array([1, 2, 3, 4, 5])
print(x < 3 )# less tha

print(x > 3 )# greater than

print(x <= 3) # less than or equal

print(x >= 3) # greater than or equal

print(x != 3 )# not equal

print(x == 3 )# equal



[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]
